<a href="https://colab.research.google.com/github/aeyjeyaryan/NLP/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.impute import SimpleImputer
import matplotlib

In [ ]:
data = pd.read_excel("Book1.xlsx")
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
X = data.iloc[: ,:-1].values
y=data.iloc[:,-1].values


In [ ]:
imputer =SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(data.iloc[:,1:3])   #iloc [startindexrow:endindexrow, startindexcol:endindexcol]
data.iloc[:,1:3]=imputer.transform(data.iloc[:,1:3])

In [ ]:
data se

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [ ]:
#categorical data
from sklearn.preprocessing import LabelEncoder    # this was on the X and Y we created earlier
labelencoder_X = LabelEncoder()
X[:,0]=labelencoder_X.fit_transform(X[:,0])

In [ ]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, nan],
       [0, 35.0, 58000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
#simple way for a 1d array
y = labelencoder_X.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#dummy encoding
from sklearn.preprocessing import *
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(max_categories = 3)
X = onehotencoder.fit_transform(X).toarray()


In [ ]:
X

array([[1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [ ]:
y   #the code is written above

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.model_selection import  train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [ ]:
X_train

array([[1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [ ]:
X_test

array([[0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 1., 0.]])

In [ ]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
y_test

array([1, 1])

In [ ]:
data

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [ ]:
X_train

array([[ 1.        , -0.57735027, -0.57735027, -0.37796447, -0.37796447,
         0.57735027, -0.37796447,  0.        ,  0.37796447],
       [-1.        ,  1.73205081, -0.57735027, -0.37796447, -0.37796447,
         0.57735027, -0.37796447,  0.        ,  0.37796447],
       [-1.        ,  1.73205081, -0.57735027, -0.37796447,  2.64575131,
        -1.73205081, -0.37796447,  0.        ,  0.37796447],
       [-1.        , -0.57735027,  1.73205081, -0.37796447, -0.37796447,
         0.57735027, -0.37796447,  0.        ,  0.37796447],
       [-1.        , -0.57735027,  1.73205081,  2.64575131, -0.37796447,
        -1.73205081,  2.64575131,  0.        , -2.64575131],
       [ 1.        , -0.57735027, -0.57735027, -0.37796447, -0.37796447,
         0.57735027, -0.37796447,  0.        ,  0.37796447],
       [ 1.        , -0.57735027, -0.57735027, -0.37796447, -0.37796447,
         0.57735027, -0.37796447,  0.        ,  0.37796447],
       [ 1.        , -0.57735027, -0.57735027, -0.37796447, -0

In [ ]:
X_test

array([[ 0.,  1., -1.,  0.,  0.,  0.,  0., -1.,  1.],
       [ 0., -1.,  1.,  0.,  0.,  0.,  0.,  1., -1.]])

In [ ]:
#working with outliers
lowerlimit = data['Age'].quantile(0.05)
lowerlimit
data[data['Age']<lowerlimit]

Country   Age   Salary Purchased
1   Spain  27.0  48000.0       Yes

In [ ]:
upperlimit = data['Age'].quantile(0.95)
upperlimit
data[data['Age']>upperlimit]

Country   Age   Salary Purchased
8  Germany  50.0  83000.0        No

In [ ]:
#removing outliers
sett = data[(data['Age']>lowerlimit) & (data["Age"]<upperlimit)]
sett

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
9   France  37.000000  67000.000000       Yes

In [ ]:

cars_data = {
    'Car': ['Toyota Camry', 'Honda Accord', 'Ford Fusion', 'Chevrolet Malibu'],
    'Year': [2022, 2023, 2022, 2023],
    'Color': ['Blue', 'Silver', 'Black', 'Red'],
    'Fuel_Type': ['Gasoline', 'Hybrid', 'Electric', 'Gasoline'],
    'Horsepower': [203, 212, 188, 250],
    'Mileage': [30, 45, 100, 28]
}

cars_data = pd.DataFrame(cars_data)

cars_data

Car  Year   Color Fuel_Type  Horsepower  Mileage
0      Toyota Camry  2022    Blue  Gasoline         203       30
1      Honda Accord  2023  Silver    Hybrid         212       45
2       Ford Fusion  2022   Black  Electric         188      100
3  Chevrolet Malibu  2023     Red  Gasoline         250       28

In [ ]:
#ordinal data into numeric values
dataMapping={
    "Blue":4,
    "Silver":3,
    "Black":2,
    "Red":1
}


In [ ]:
cars_data['Colorcode']=cars_data['Color'].map(dataMapping)
cars_data

Car  Year   Color Fuel_Type  Horsepower  Mileage  Colorcode
0      Toyota Camry  2022    Blue  Gasoline         203       30          4
1      Honda Accord  2023  Silver    Hybrid         212       45          3
2       Ford Fusion  2022   Black  Electric         188      100          2
3  Chevrolet Malibu  2023     Red  Gasoline         250       28          1